# Cloudflare Pages 前端配置
name = "dongshihui-frontend"
pages_build_output_dir = "build"

[build]
command = "npm run build"
cwd = "."

# 兼容性配置
compatibility_date = "2024-01-01"

# 路由配置
[[redirects]]
from = "/api/*"
to = "https://dongshihui-api.your-subdomain.workers.dev/:splat"
status = 200