name = "dongshihui-api"
main = "workers/index.js"
compatibility_date = "2024-01-01"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "dongshihui-db"
database_id = "741c830e-ffcf-4231-b104-90af2d90da59"

# KV存储配置
[[kv_namespaces]]
binding = "KV"
id = "7cea8217ea1f466ba3de2a323ea2c8a1"

# 环境变量 (敏感信息请在Cloudflare Dashboard中配置)
[vars]
NODE_ENV = "production"