name = "dongshihui-api"
main = "workers/index.js"
compatibility_date = "2024-01-01"

# 环境变量
[env.production.vars]
NODE_ENV = "production"

# D1 数据库配置 (替代PostgreSQL)
[[env.production.d1_databases]]
binding = "DB"
database_name = "dongshihui-db"
database_id = ""  # 需要在Cloudflare创建D1数据库后填入

# KV存储配置 (用于会话管理)
[[env.production.kv_namespaces]]
binding = "KV"
id = ""  # 需要在Cloudflare创建KV命名空间后填入

# 开发环境配置
[env.development]
name = "dongshihui-api-dev"

[[env.development.d1_databases]]
binding = "DB"
database_name = "dongshihui-db-dev"
database_id = ""

[[env.development.kv_namespaces]]
binding = "KV"
id = ""

# 部署配置
[build]
command = "npm run build:worker"
cwd = "."

# 静态文件服务
[site]
bucket = "./frontend/build"
entry-point = "workers"