name = "dongshihui-api"
main = "workers/index.js"
compatibility_date = "2024-01-01"

# 环境变量
[env.production.vars]
NODE_ENV = "production"

# D1 数据库配置 (替代PostgreSQL)
[[env.production.d1_databases]]
binding = "DB"
database_name = "dongshihui-db"
database_id = "741c830e-ffcf-4231-b104-90af2d90da59"

# KV存储配置 (用于会话管理)
[[env.production.kv_namespaces]]
binding = "KV"
id = "7cea8217ea1f466ba3de2a323ea2c8a1"

# 开发环境配置
[env.development]
name = "dongshihui-api-dev"

[[env.development.d1_databases]]
binding = "DB"
database_name = "dongshihui-db"
database_id = "741c830e-ffcf-4231-b104-90af2d90da59"

[[env.development.kv_namespaces]]
binding = "KV"
id = "7cea8217ea1f466ba3de2a323ea2c8a1"

# 部署配置
[build]
command = "npm run build:worker"
cwd = "."